### ISSUE TITLE
ImagesOfColorado update

### ISSUE THREAD

**Issue by amici-ursi** [amici-ursi/ImagesOfNetwork#101]
https://www.reddit.com/message/messages/6ew32a

> Hey - I use the subreddit r/sips, a subreddit about a YouTuber. I've noticed that quite often images people post there are instantly posted onto your subreddit by, I assume, your bot
> So yeah, that's it really.

**Comment by SmithsonianDSP** [comment]
added /r/sips to the /r/ImagesOfNetwork subreddit blacklist
