### ISSUE TITLE
Double comments

### ISSUE THREAD

**Issue by amici-ursi** [amici-ursi/ImagesOfNetwork#15]
Sometimes the bot makes two source comments.
- https://www.reddit.com/r/ImagesOfIndia/comments/4fa09w
- https://www.reddit.com/r/ImagesOfIndia/comments/4fa0ne

**Comment by SmithsonianDSP** [comment]
https://www.reddit.com/r/ImagesOfWisconsin/comments/4gizhy/madison_wisconsin_north_carroll_street_ca_1890/

**Comment by amici-ursi** [comment]
https://www.reddit.com/r/ImagesOfDelaware/comments/4go8x1/greeks_mourning_their_dead_after_turks_set_fire/

**Comment by amici-ursi** [comment]
_sighs_

https://www.reddit.com//r/ImagesOfVermont/comments/4h1use/university_of_vermont_burlington_vermont_ca_1903/

**Comment by SmithsonianDSP** [comment]
#27 Doesn't seem to have fixed this:
- https://www.reddit.com/r/ImagesOfGeorgia/comments/4hhm7p/pulaski_house_savannah_georgia_1906_pulaski_house/
- https://www.reddit.com/r/ImagesOfCalifornia/comments/4hhtze/on_the_ruins_april_1906_chinatown_san_francisco/
