### ISSUE TITLE
error on running subreddit_setup_and_copy.py

### ISSUE THREAD

**Issue by amici-ursi** [amici-ursi/ImagesOfNetwork#16]
```
Traceback (most recent call last):
  File "subreddit_setup_and_copy.py", line 102, in main
    ret = whipslaves(reddit_session, base_settings, do_mods, base_mods)
  File "subreddit_setup_and_copy.py", line 33, in whipslaves
    if add_to_multi:
UnboundLocalError: local variable 'add_to_multi' referenced before assignment
```

**Comment by SmithsonianDSP** [comment]
@amici-ursi: is this issue still applicable, post-@scowcron's rewrite?

**Comment by amici-ursi** [comment]
Presumably not, but I haven't tested the new code. Will do today.

**Comment by scowcron** [comment]
For the record:

`ion_expand` is the new script you're talking about. It's a little different from `subreddit_setup_and_copy.py`. That script was similar to hot_sister, where it was set up to loop and continually update all sub settings to match the parent. `ion_expand` only creates a new sub and sets it up once.

**Comment by amici-ursi** [comment]
closed because we're no longer using this script.
