### ISSUE TITLE
Add a local log of submissions to prevent duplicates

### ISSUE THREAD

**Issue by amici-ursi** [amici-ursi/ImagesOfNetwork#27]
1. Check if URL and subreddit combo are in the log
2. If not, make post
3. add URL and subreddit to the the log
4. limit log to `n` items by removing the oldest when a new entry is added.

related to #15

**Comment by SmithsonianDSP** [comment]
Potentially useful reading: 
- http://chrisdail.com/2008/12/19/queue-based-on-a-dictionary-in-python/
- https://docs.python.org/2/library/collections.html
- http://www.dotnetperls.com/dictionary-python 
-  http://stackoverflow.com/q/4391697/5012594

Not sure which, of any, of these will be useful for this, but it seems like they might be on the right track. 

(Also posting them here so I can read them later...)

**Comment by amici-ursi** [comment]
Noted. Thanks

Info on why not to use  `queue`: http://stackoverflow.com/questions/16506429/check-if-element-is-already-in-a-queue

~~Maybe this instead https://docs.python.org/3/library/collections.html#ordereddict-objects~~ nah
