### ISSUE TITLE
Update AutoMod config update script to prevent overwriting individual subreddit custom rules

### ISSUE THREAD

**Issue by SmithsonianDSP** [amici-ursi/ImagesOfNetwork#29]
Need to update the AutoMod config update script so that it does not overwrite the entire subreddit config when pushing out updated network-wide rules. 

Similar to the sidebar update method, the script would identify the network rules section by only replacing the config section between the section start/end flags:

```
#Begin-Network-Config

...

#End-Network-Config
```

**Comment by scowcron** [comment]
`ion_propagate --automod` does this now.
