### ISSUE TITLE
Better user-requested blacklisting

### ISSUE THREAD

**Issue by amici-ursi** [amici-ursi/ImagesOfNetwork#34]
When a user requests to be blacklisted, they send a modmail and we manually add that user to `/r/imagesofnetwork/wiki/userblacklist`. That is fine, but the process could be automated.

**Comment by SmithsonianDSP** [comment]
[Here's the initial version of the script that I've written to do this](https://gist.github.com/SmithsonianDSP/844e33cfae6a3b46d266b5323c563708/). As @scowcron suggested, this would probably be set to run as a cron job.

It only processes modmail messages that have the words 'blacklist me' in the subject and/or body and have _**not**_ been replied to by another moderator, yet. If a message matches the criteria, it will check to see if the user is already in the global blacklist; if not, it will reply to the user and then add them to the blacklist list. (The user blacklist is also sorted, converter to all lowercase, and deduped.)

Tested and appears to be working on my private subreddit but would like @scowcron and @amici-ursi to review and provide feedback.

**Comment by SmithsonianDSP** [comment]
[Addressed with latest commit](https://github.com/amici-ursi/ImagesOfNetwork/commit/2143fce84957ae93896de59c67c10b3b7ec7bebb).
