### ISSUE TITLE
Update sidebar, FAQ, et. al., for inclusion of ImagesOfTheDecades

### ISSUE THREAD

**Issue by SmithsonianDSP** [amici-ursi/ImagesOfNetwork#70]
Making a list of things that will need to be updated or checked to ensure they reflect the inclusion of the ImagesOfTheDecades into the fold, as well.
- [x] Sidebar (not just "places," anymore)
- [x] Hot-Sister 
- [x] FAQ
- [x] ImagesOfTheDecades Multireddit links

**Comment by amici-ursi** [comment]
related to #4

**Comment by amici-ursi** [comment]
That should be all the things.
